# Generated by Django 4.2.3 on 2023-07-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alunos',
            new_name='Aluno',
        ),
    ]
